### ISSUE TITLE
Fix g++-9 warnings

### ISSUE THREAD

**Issue by MrX0r** [aaelick/VanitySearch-bitcrack#1]
These 3 small warnings and blemishes have crept in which are caused under Linux with g++-9

`main.cpp: In function ‘void checkKeySpace(BITCRACK_PARAM*, Int&)’:
main.cpp:191:52: warning: '0' flag used with ‘%s’ gnu_printf format [-Wformat=]
191 |   fprintf(stderr, "[ERROR] START/END IsGreater %064s \n", maxKey.GetBase16().c_str());`

`main.cpp: In function ‘void outputAdd(std::string, int, std::string, std::string, std::string)’:
main.cpp:310:32: warning: '0' flag used with ‘%s’ gnu_printf format [-Wformat=]
  310 |  fprintf(f, "Priv (HEX): 0x%064s\n", pAddrHex.c_str());`

`main.cpp: In function ‘void getKeySpace(const string&, BITCRACK_PARAM*, Int&)’:
main.cpp:171:10: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
 171 |     scanf(&item[2 * i], "%02hhX", &my1ch);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

https://github.com/aaelick/VanitySearch-bitcrack/blob/6d478d4aeedb29e5e52df2696300760e11663207/main.cpp#L171
`sscanf(&item[2 * i], "%02hhX", &my1ch);`
Solution with sscanf: Will the error be fixed

https://github.com/aaelick/VanitySearch-bitcrack/blob/6d478d4aeedb29e5e52df2696300760e11663207/main.cpp#L191
`fprintf(stderr, "[ERROR] START/END IsGreater %s \n", maxKey.GetBase16().c_str());`
The change solves the problem

https://github.com/aaelick/VanitySearch-bitcrack/blob/6d478d4aeedb29e5e52df2696300760e11663207/main.cpp#L310
`fprintf(f, "Priv (HEX): 0x%s\n", pAddrHex.c_str());`
The change will fix the problem

--------------------------------------------------------------------------------------------------------------------

Under Visual Studio 2019 this warning is displayed below

I haven't found a solution for it there
Severity Code Description Project File Line Suppression State Details
```
Warning C6031 Return value ignored: "sscanf". VanitySearch main.cpp 131
Warning C6031 Return value ignored: "sscanf". VanitySearch main.cpp 150
Warning C6031 Return value ignored: "sscanf". VanitySearch main.cpp 171
```

**Comment by aaelick** [comment]
fixed

**Comment by aaelick** [comment]
fixed
