### ISSUE TITLE
Ubuntu 20.04.4 / error while exiting

### ISSUE THREAD

**Issue by MrX0r** [aaelick/VanitySearch-bitcrack#2]
Extract from the error no bending although he is finished with the range

(2^39.98) [00:02:12 RUN || END 00:00:01] [0]
(2^39.99) [00:02:13 RUN || END 00:00:00] [0]
(2^40.00) [00:02:14 RUN || END ...finishing][0]
(2^40.01) [00:02:15 RUN || END ...finishing][0]
(2^40.02) [00:02:16 RUN || END ...finishing][0]
Which takes over 10 minutes

Under this Ubuntu version which is used on clore.ai the program does not terminate, it only does so after more than 10 minutes!
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

Under this Ubuntu version the program will terminate correctly when it has completely searched the range

**[EXIT] Range search completed**

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy

**Comment by aaelick** [comment]
Hello. Are you sure you using latest version? Thanks.

**Comment by aaelick** [comment]
This error was in earlier version. Now I'm using current version over a month without this issue including a lot of clore.ai rentals. No error. Very strange you have it.

**Comment by aaelick** [comment]
You can use only one GPU at time. Run separate instance for every GPU.

**Comment by aaelick** [comment]
Just added this to readme.
It difficult to sync multiple gpus at once in one rig, because even same gpus will have some slight variations in performance.

**Comment by aaelick** [comment]
To prevent skipping keys.
